config/routes.rb
Rails.application.routes.draw do
  resources :posts, only: [:index, :create]
  root 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include CableReady::Broadcaster
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order(created_at: :desc)
    @post = Post.new
  end

  def create
    post = Post.create(post_params)
    cable_ready["timeline"].insert_adjacent_html(
      selector: "#timeline",
      position: "afterbegin",
      html: render_to_string(partial: "post", locals: {post: post})
    )
    cable_ready.broadcast
    redirect_to posts_path
  end
  private

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" 
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: @post, local: true,html: {class: "my-4"}) do |form| %>
<div class="form-group">
   <%= form.text_area :body, placeholder: "Ender yout message", class: "form-control", rows: 3%>
</div>
<div class="actions">
    <%= form.submit class: "btn btn-primary"%>
 </div>   
<% end %>

app/views/posts/_post.html.erb
<div class="card mb-2">
   <div class="card-body">
      <h5 class="card-title text-muted">
      <%= post.username %>
      <small> - <%= time_ago_in_words post.created_at%></small>
      </h5>
      <div class="card-text lead mb-2"><%= post.body %></div>
        <%= link_to "#", class: "card-link", data: {reflex: "click->PostsReflex#repost", id: post.id} do %>
          Repost (<%= tag.span post.repost_count, id: "post-#{post.id}-repost" %>
        <% end %>
        <%= link_to "#", class: "card-link", data: {reflex: "click->PostsReflex#like", id: post.id} do %>
          like (<%= tag.span post.likes_count, id: "post-#{post.id}-likes" %>
        <% end %>
   </div>
  </div> 

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="container">
<h1>Chatter</h1>
<h4>A CableReady &amp; StimulusReflex</h4>

<%= render 'form' %>

<div id="timeline">
<%= render partial: "post", collection: @posts %>
</div>



</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @post.username %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>Likes count:</strong>
  <%= @post.likes_count %>
</p>

<p>
  <strong>Repost count:</strong>
  <%= @post.repost_count %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>